create table CLIENTE (
  ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(255),
  SOBRENOME VARCHAR(255),
  PRIMARY KEY (ID_CLIENTE)
);

create table FORNECEDOR (
  ID_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(255),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(255),
  CIDADE VARCHAR(255),
  ESTADO VARCHAR(255),
  PAIS  VARCHAR(255),
  MUNDO VARCHAR(255),
  CEP INT,
  PRIMARY KEY (ID_FORNECEDOR),
);

create table TELEFONE (
  ID_TELEFONE INT NOT NULL AUTO_INCREMENT,
  NUMERO BIGINT NOT NULL,
  ID_CLIENTE INT,
  ID_FORNECEDOR INT,
  PRIMARY KEY (ID_TELEFONE),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

create table ENDERECO (
  ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INT,
  ID_FORNECEDOR INT,
  RUA VARCHAR(255),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(255),
  CIDADE VARCHAR(255),
  ESTADO VARCHAR(255),
  PAIS  VARCHAR(255),
  MUNDO VARCHAR(255),
  CEP INT,
  PRIMARY KEY (ID_ENDERECO),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
  
);

create table PRODUTO (
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(255),
  FABRICANTE VARCHAR(255),
  VALIDADE DATE,
  PRIMARY KEY (ID_PRODUTO)
);

create table PRODUTO_FORNECEDOR (
  ID_PRODUTO INT,
  ID_FORNECEDOR INT,
  FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
  FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
 );